SELECT coluna1,coluna2
FROM tabela

SELECT * (Todas)
FROM tabela

/*
[Desafio]

A EQUIPE DE MARKETING PRECISA DE FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA

[Resolução]
*/

SELECT firstName,lastName
FROM person.Person